[testServer]
BROKER_HOST = ${rabbitmq_server_ip}
BROKER_PORT = 5672
USER = ${rabbitmq_user}
PASSWORD = ${rabbitmq_password}
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

